# Generated by Django 4.1.2 on 2024-06-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('carrera', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
